name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest
    - name: Run Ruff Linting
      run: ruff check .
    - name: Run Tests
      run: |
        export DATABASE_URL="mongodb://localhost:27017/testdb"
        export SECRET_KEY="secret-key"
        pytest
